### ISSUE TITLE
Fixing or Refreshing Action Items doesn't re-evaluate warnings

### ISSUE THREAD

**Issue by david-hall** [jlahoda/nb-code-recommenders#1]
After correcting (or causing) an issue that qualifies as a warning, the only way I can get the Action Item window to recognize it is to restart NetBeans. (Maybe unloading and reloading the project would work, but even if it did, that wouldn't be an acceptable solution.)

For example, I have a variable in a java class that can be final. A warning is generated as expected, but when I change it to final, save the file, rebuild the project and then refresh the Action Items window, the warning still doesn't go away.

Similarly, if I have a final variable and remove the 'final' designation, no warning is generated.

Another condition that behaves similarly is an unused variable. 

Here's a simple class that contains both conditions and exhibits the problem:

```
public class Foo {
    private int bar; // Field bar can be final
    private final int car; // Field car is not used
    public Foo(int b, int c) {
        this.bar = b;
        this.car = c;
    }
    public int getBar() {
        return bar;
    }
}
```

If there's something simple I can do to refresh the Action Items window, please let me know, but it's not currently working as expected. I would expect it to be automatic, at least when the file is saved, but a refresh from the context menu should work at any time.

I'm running on a 64 bit Windows 7 machine using version 1.2.0.1.13 of the "Java Hints to Action Window" plugin with NetBeans IDE 8.0.2 (Build 201411181905). As far as I know this is the most recent version of both.

Thanks,
David

**Comment by david-hall** [comment]
The problem is also mentioned at https://netbeans.org/bugzilla/show_bug.cgi?id=236431

**Comment by david-hall** [comment]
I just discovered that saving the file then switching the filter from "currently edited file" to "all opened projects" and back to "currently edited file" will refresh the list. It's not as automatic as I'd hope, but it's certainly usable now that I know the trick. Still, it seems like refreshing from the context menu should work as well. Auto refreshing upon saving the file would be nice too.

**Comment by markiewb** [comment]
@david-hall: I don't understand, what your reported issue has to do with this plugin.

This plugin is about code completion. Your issue is about the tasks/action items view.

**Comment by david-hall** [comment]
Sorry, my mistake. For some reason I thought this was the project for the  "Java Hints to Action Window" plugin at http://plugins.netbeans.org/plugin/54834/java-hints-to-actions-window. Now I'm not sure now how I got that idea. I think that it started because that plugin's "owner" is "jlahoda", the same as the owner of this git repository. Any chance it's the same person? If so, is there any way you could pass along this issue? Again, sorry for my mistake.

**Comment by markiewb** [comment]
@david-hall: Yes, the owner is correct. File your issue at https://bitbucket.org/jlahoda/nb-warnings-in-actions-window

**Comment by david-hall** [comment]
Done. Thanks for pointing me to the correct owner.
